In [1]:
import os
import sys

from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
import SimpleITK as sitk
import nrrd
import vtk

import torch
from torch import nn
from torch.nn import functional as F
from torchvision import transforms

import pytorch_lightning as pl
import pickle
import monai 
import glob 
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


sys.path.append('/mnt/raid/C1_ML_Analysis/source/famli-ultra-sim/')
sys.path.append('/mnt/raid/C1_ML_Analysis/source/famli-ultra-sim/dl')
import dl.loaders.ultrasound_dataset as ultrasound_dataset
import dl.transforms.ultrasound_transforms as ultrasound_transforms
import dl.nets.us_simulation_jit as us_simulation_jit
import dl.nets.us_simu as us_simu

import importlib

from pytorch3d.ops import (knn_points, 
                           knn_gather)

sys.path.append('/mnt/raid/C1_ML_Analysis/source/ShapeAXI/src/')
from shapeaxi.saxi_layers import SelfAttention

In [2]:
def plot_diffusion(X, P=None, frame=None, scale=10):
    num_surf = len(X)
    specs_r = [{'type': 'scatter3d'} for _ in range(num_surf)]

    fig = make_subplots(
        rows=1, cols=num_surf,
        specs=[specs_r]
    )

    for idx, x in zip(range(num_surf), X):
        # First scatter plot
        fig.add_trace(
            go.Scatter3d(x=x[:,0], y=x[:,1], z=x[:,2], mode='markers', marker=dict(
                size=2,
                color=x[:,2],                # set color to an array/list of desired values
                colorscale='Viridis',   # choose a colorscale
                opacity=0.8
            )),
            row=1, col=idx+1
        )

    if P is not None:
        for idx, p in zip(range(num_surf), P):
            fig.add_trace(
                go.Scatter3d(x=p[:,0], y=p[:,1], z=p[:,2], mode='markers', marker=dict(
                    size=4,
                    color='red',                # set color to an array/list of desired values
                    opacity=1,
                )),
                row=1, col=idx+1
            )

    if frame is not None:
        for idx, f in zip(range(num_surf), frame):

            if P is None:
                origin = np.zeros((3,))
            else:
                origin = P[idx,0]

            for i in range(3):
                fig.add_trace(go.Scatter3d(
                    x=[origin[0], origin[0] + f[i, 0]*scale],
                    y=[origin[1], origin[1] + f[i, 1]*scale],
                    z=[origin[2], origin[2] + f[i, 2]*scale],
                    mode='lines',
                    line=dict(color='cyan', width=8),
                ), 
                row=1, col=idx+1)

    return fig

def compute_orthogonal_frame(points: torch.Tensor) -> torch.Tensor:    
    """
    Given a tensor of shape [B, 3, 3] representing three 3D points per batch,
    returns a tensor of shape [B, 3, 3] representing an orthogonal frame [x, y, z] for each batch.
    """
    p0 = points[:, 0]
    p1 = points[:, 1]
    p2 = points[:, 2]
    
    v1 = p1 - p0
    v2 = p2 - p0

    # Normalize x (first direction)
    x = F.normalize(v1, dim=1)

    # Compute z = normalized cross(v1, v2)
    z = F.normalize(torch.cross(v1, v2, dim=1), dim=1)

    # Compute y = cross(z, x)
    y = torch.cross(z, x, dim=1)

    # Stack the vectors as rows of the rotation matrix
    frame = torch.stack([x, y, z], dim=1)  # [B, 3, 3]

    return frame

In [3]:
# fig = plot_diffusion(X_PC.cpu().numpy())
# fig.show()

In [4]:
# p = torch.tensor([[0.04572, 0.6788, 0.5607], [-3.0951, 0.1676, -1.2842], [0.3316, -8.0302, 0.38299]]) # hands on head model. We picked a point on the head, the belly and shoulder 
# dist = knn_points(p.unsqueeze(0), X_PC, K=1)
# dist.idx
# idx = dist.idx

# idx = torch.tensor([[[1470],
#          [3369],
#          [2043]]])

# k = knn_gather(X_PC, idx).squeeze(2)

# frame = compute_orthogonal_frame(k)
# plot_diffusion(X_PC.cpu().numpy(), k.cpu().numpy(), frame.cpu().numpy())

In [5]:
rest = np.load("/mnt/raid/C1_ML_Analysis/simulated_data_export/fetus_rest_selected/rest.npy")

head = np.load("/mnt/raid/C1_ML_Analysis/simulated_data_export/fetus_rest_selected/head.npy")
belly = np.load("/mnt/raid/C1_ML_Analysis/simulated_data_export/fetus_rest_selected/belly.npy")
side = np.load("/mnt/raid/C1_ML_Analysis/simulated_data_export/fetus_rest_selected/side.npy")

In [6]:
rest_pc = torch.tensor(rest).to(torch.float32)
head_pc = torch.tensor(head).unsqueeze(0).to(torch.float32)
belly_pc = torch.tensor(belly).unsqueeze(0).to(torch.float32)
side_pc = torch.tensor(side).unsqueeze(0).to(torch.float32)

In [7]:
side_pc.shape

torch.Size([1, 3, 3])

In [8]:
rest_pc.shape

torch.Size([1, 4096, 3])

In [9]:

dist = knn_points(head_pc, rest_pc, K=1)
head_idx = dist.idx

head_k = knn_gather(rest_pc, head_idx).squeeze(2)

dist = knn_points(belly_pc, rest_pc, K=1)
belly_idx = dist.idx
belly_k = knn_gather(rest_pc, belly_idx).squeeze(2)

dist = knn_points(side_pc, rest_pc, K=1)
side_idx = dist.idx
side_k = knn_gather(rest_pc, side_idx).squeeze(2)

rest_points = torch.stack([torch.mean(belly_k, dim=1), 
                           torch.mean(head_k, dim=1),
                           torch.mean(side_k, dim=1)], dim=1)

frame_rest = compute_orthogonal_frame(rest_points)
plot_diffusion(rest_pc.cpu().numpy(), rest_points.cpu().numpy(), frame_rest.cpu().numpy(), scale=1)

In [10]:
batch_size = 4
dm = ultrasound_dataset.ImgPCDataModule(
    mount_point="/mnt/raid/C1_ML_Analysis/simulated_data_export",
    csv_train="simulated_data_export/studies_fetus_train_train.csv",
    np_train="simulated_data_export/studies_fetus_train_train.npy",
    csv_valid="simulated_data_export/studies_fetus_train_test.csv",
    np_valid="simulated_data_export/studies_fetus_train_test.npy",
    csv_test="simulated_data_export/studies_fetus_test.csv",
    np_test="simulated_data_export/studies_fetus_test.npy",
    num_samples_train=5000,
    rescale_factor=10,
    batch_size=1
    )
dm.setup()

In [11]:
dl_test = dm.test_dataloader()
it = iter(dl_test)

In [12]:
X, X_origin, X_end, X_PC = next(it)
X = X[0:1]
X_origin = X_origin[0:1] 
X_end = X_end[0:1]
X_PC = X_PC[0:1]

In [13]:

pc_head_k = knn_gather(X_PC, head_idx).squeeze(2)
pc_belly_k = knn_gather(X_PC, belly_idx).squeeze(2)
pc_side_k = knn_gather(X_PC, side_idx).squeeze(2)

points = torch.stack([torch.mean(pc_belly_k, dim=1),
                      torch.mean(pc_head_k, dim=1),
                      torch.mean(pc_side_k, dim=1)], dim=1)

frame = compute_orthogonal_frame(points)
plot_diffusion(X_PC.cpu().numpy(), points.cpu().numpy(), frame.cpu().numpy(), scale=1.0)

In [14]:
# np.save("/mnt/raid/C1_ML_Analysis/simulated_data_export/fetus_rest_selected/head_idx.npy", head_idx.cpu().numpy())
# np.save("/mnt/raid/C1_ML_Analysis/simulated_data_export/fetus_rest_selected/belly_idx.npy", belly_idx.cpu().numpy())
# np.save("/mnt/raid/C1_ML_Analysis/simulated_data_export/fetus_rest_selected/side_idx.npy", side_idx.cpu().numpy())

In [19]:
from shapeaxi import utils
import ast

mount_point = "/mnt/raid/C1_ML_Analysis/simulated_data_export/animation_export"
df = pd.read_csv("/mnt/raid/C1_ML_Analysis/simulated_data_export/animation_export/animation_export_fetus_frame.csv")

row = df.sample(n=1).reset_index(drop=True).iloc[0]
surf = utils.ReadSurf(os.path.join(mount_point, row['surf']))
X, V = utils.PolyDataToTensors_v_f(surf)

frame = np.array(ast.literal_eval(row['frame'])).reshape(1, 3, 3)

plot_diffusion(X.unsqueeze(0).cpu().numpy(), frame=frame, scale=0.1)

In [22]:
df_poses = pd.read_csv('/mnt/raid/C1_ML_Analysis/simulated_data_export/animation_export/all_poses_sweeps_us.csv')
df_frame = pd.read_csv('/mnt/raid/C1_ML_Analysis/simulated_data_export/animation_export/animation_export_fetus_frame.csv')

In [23]:
df_frame['study_id'] = df_frame['surf'].apply(lambda x: x.split('/')[1])

In [25]:
df_frame

,surf,frame,study_id
0,all_poses/frame_0001/fetus/Fetus_Model.stl,"[-0.3439772129058838, 0.892949104309082, 0.290...",frame_0001
1,all_poses/frame_0002/fetus/Fetus_Model.stl,"[-0.34501007199287415, 0.8927798867225647, 0.2...",frame_0002
2,all_poses/frame_0003/fetus/Fetus_Model.stl,"[-0.3479907214641571, 0.8922820687294006, 0.28...",frame_0003
3,all_poses/frame_0004/fetus/Fetus_Model.stl,"[-0.3527316749095917, 0.8914783000946045, 0.28...",frame_0004
4,all_poses/frame_0005/fetus/Fetus_Model.stl,"[-0.35903844237327576, 0.8903988003730774, 0.2...",frame_0005
...,...,...,...
1195,all_poses/frame_1196/fetus/Fetus_Model.stl,"[0.1463327556848526, -0.8959002494812012, -0.4...",frame_1196
1196,all_poses/frame_1197/fetus/Fetus_Model.stl,"[0.14522388577461243, -0.8963669538497925, -0....",frame_1197
1197,all_poses/frame_1198/fetus/Fetus_Model.stl,"[0.14442142844200134, -0.8967011570930481, -0....",frame_1198
1198,all_poses/frame_1199/fetus/Fetus_Model.stl,"[0.1439342051744461, -0.8969020247459412, -0.4...",frame_1199
1199,all_poses/frame_1200/fetus/Fetus_Model.stl,"[0.14376971125602722, -0.8969692587852478, -0....",frame_1200

In [29]:
df_poses_frame = df_poses.merge(df_frame[['frame', 'study_id']], on='study_id', how='left')

In [30]:
df_poses_frame.to_csv('/mnt/raid/C1_ML_Analysis/simulated_data_export/animation_export/all_poses_sweeps_us_frame.csv', index=False)

In [31]:
df_poses_frame

,file_path,tag,study_id,presentation,frame
0,all_poses_sweeps_us/all_poses/frame_0608/M.nrrd,M,frame_0608,1,"[0.36439844965934753, 0.8230748772621155, -0.4..."
1,all_poses_sweeps_us/all_poses/frame_0608/L0.nrrd,L0,frame_0608,1,"[0.36439844965934753, 0.8230748772621155, -0.4..."
2,all_poses_sweeps_us/all_poses/frame_0608/L1.nrrd,L1,frame_0608,1,"[0.36439844965934753, 0.8230748772621155, -0.4..."
3,all_poses_sweeps_us/all_poses/frame_0608/R0.nrrd,R0,frame_0608,1,"[0.36439844965934753, 0.8230748772621155, -0.4..."
4,all_poses_sweeps_us/all_poses/frame_0608/R1.nrrd,R1,frame_0608,1,"[0.36439844965934753, 0.8230748772621155, -0.4..."
...,...,...,...,...,...
10795,all_poses_sweeps_us/all_poses/frame_1197/R1.nrrd,R1,frame_1197,0,"[0.14522388577461243, -0.8963669538497925, -0...."
10796,all_poses_sweeps_us/all_poses/frame_1197/C1.nrrd,C1,frame_1197,0,"[0.14522388577461243, -0.8963669538497925, -0...."
10797,all_poses_sweeps_us/all_poses/frame_1197/C2.nrrd,C2,frame_1197,0,"[0.14522388577461243, -0.8963669538497925, -0...."
10798,all_poses_sweeps_us/all_poses/frame_1197/C3.nrrd,C3,frame_1197,0,"[0.14522388577461243, -0.8963669538497925, -0...."
10799,all_poses_sweeps_us/all_poses/frame_1197/C4.nrrd,C4,frame_1197,0,"[0.14522388577461243, -0.8963669538497925, -0...."