In [1]:
import pandas as pd
import plotly
import plotly.express as px
import os
import glob

In [2]:
df = pd.read_csv("/mnt/raid/C1_ML_Analysis/CSV_files/ALL_C2_cines_gt_ga_withmeta_20221031_butterfly_train.csv")

/mnt/raid/home/jprieto/tmp/ipykernel_2593257/4276483297.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/mnt/raid/C1_ML_Analysis/CSV_files/ALL_C2_cines_gt_ga_withmeta_20221031_butterfly_train.csv")

In [3]:
df.columns

Index(['Unnamed: 0', 'tag', 'fetal_presentation_str', 'study_id', 'file_path',
       'dvp_crf', 'fetal_presentation', 'study_instance_n', 'model',
       'file_name', 'spacing_x', 'spacing_y', 'n_rows', 'n_columns',
       'n_frames.1', 'session_id', 'n_frames', 'gatool_session',
       'famli_session_id', 'ga_boe', 'ga_expert', 'famli_edd_source',
       'famli_edd_source_detail', 'ga_absdiff', 'is_anchor', 'new_n_frames',
       'new_n_frames.1', 'pid', 'ineligible', 'twin'],
      dtype='object')

In [6]:
df

,Unnamed: 0,tag,fetal_presentation_str,study_id,file_path,dvp_crf,fetal_presentation,study_instance_n,model,file_name,...,ga_expert,famli_edd_source,famli_edd_source_detail,ga_absdiff,is_anchor,new_n_frames,new_n_frames.1,pid,ineligible,twin
0,16,NaN,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,3.0,Butterfly Network Inc,557b5175-b398-47f8-b2fd-f783b3fa2cbe.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
1,17,NaN,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,5.0,Butterfly Network Inc,13a6a755-4669-4af0-94c0-9b1c54087b8d.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
2,18,ASSBS,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,7.0,Butterfly Network Inc,27bd7584-5ae1-4373-b998-5c5e4038b78c.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
3,19,ASSBS,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,8.0,Butterfly Network Inc,2f4dfcad-791b-4558-a21c-80851798c2d5.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
4,20,ASSBS,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,9.0,Butterfly Network Inc,cbf4371f-7aa3-404f-9526-fd10fcd16f26.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51350,97483,NL,Breech,FAM-025-1348-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,2,30.0,Butterfly Network Inc,eb83cfdb-66db-4330-9f7f-9ea67fe5b156.nrrd,...,103.961612,ZAM-AnchorInTrim2,IG_HCFL,4.263256e-14,1,NaN,NaN,FAM-025-1348,0,1.0
51351,97484,NR,Breech,FAM-025-1348-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,2,31.0,Butterfly Network Inc,af79dca9-2b1f-4b10-8bd9-7c7566706895.nrrd,...,103.961612,ZAM-AnchorInTrim2,IG_HCFL,4.263256e-14,1,NaN,NaN,FAM-025-1348,0,1.0
51352,97485,NC1,Breech,FAM-025-1348-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,2,32.0,Butterfly Network Inc,57fa87d6-4558-4833-b7bb-7dea36d67999.nrrd,...,103.961612,ZAM-AnchorInTrim2,IG_HCFL,4.263256e-14,1,NaN,NaN,FAM-025-1348,0,1.0
51353,97486,NC2,Breech,FAM-025-1348-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,2,33.0,Butterfly Network Inc,ddf4ac07-7d03-4c85-b4c9-e06d895dc677.nrrd,...,103.961612,ZAM-AnchorInTrim2,IG_HCFL,4.263256e-14,1,NaN,NaN,FAM-025-1348,0,1.0
51354,97487,NC3,Breech,FAM-025-1348-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,2,34.0,Butterfly Network Inc,1ea9d9c6-2a18-44bc-b4b3-b3fc831d5f69.nrrd,...,103.961612,ZAM-AnchorInTrim2,IG_HCFL,4.263256e-14,1,NaN,NaN,FAM-025-1348,0,1.0

In [8]:
df.query('n_frames >= 64 and n_frames < 400')

,Unnamed: 0,tag,fetal_presentation_str,study_id,file_path,dvp_crf,fetal_presentation,study_instance_n,model,file_name,...,ga_expert,famli_edd_source,famli_edd_source_detail,ga_absdiff,is_anchor,new_n_frames,new_n_frames.1,pid,ineligible,twin
0,16,NaN,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,3.0,Butterfly Network Inc,557b5175-b398-47f8-b2fd-f783b3fa2cbe.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
1,17,NaN,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,5.0,Butterfly Network Inc,13a6a755-4669-4af0-94c0-9b1c54087b8d.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
2,18,ASSBS,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,7.0,Butterfly Network Inc,27bd7584-5ae1-4373-b998-5c5e4038b78c.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
3,19,ASSBS,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,8.0,Butterfly Network Inc,2f4dfcad-791b-4558-a21c-80851798c2d5.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
4,20,ASSBS,Cephalic,UNC-0529-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,7,1,9.0,Butterfly Network Inc,cbf4371f-7aa3-404f-9526-fd10fcd16f26.nrrd,...,212.528204,UNC EPIC,LAST MENSTRUAL PERIOD,8.528204e+00,1,NaN,NaN,UNC-0529,0,-88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51319,97392,BPD,Breech,FAM-025-1338-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,5,2,7.0,Butterfly Network Inc,35fabca2-e603-4165-b2b4-3eb2be035e67.nrrd,...,136.110498,ZAM-AnchorInTrim2,IG_HCFL,1.080025e-12,1,NaN,NaN,FAM-025-1338,0,1.0
51341,97474,NM,Variable,FAM-025-1347-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,4,11.0,Butterfly Network Inc,909b8ebb-1289-4fa7-9c60-5398de332ee1.nrrd,...,86.417091,ZAM-AnchorInTrim1,IG_CRL,1.989520e-13,1,NaN,NaN,FAM-025-1347,0,1.0
51344,97477,NC1,Variable,FAM-025-1347-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,4,14.0,Butterfly Network Inc,f9a26958-5281-4d34-856e-6ee9caccf28c.nrrd,...,86.417091,ZAM-AnchorInTrim1,IG_CRL,1.989520e-13,1,NaN,NaN,FAM-025-1347,0,1.0
51346,97479,NC3,Variable,FAM-025-1347-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,4,16.0,Butterfly Network Inc,22454e36-8ced-4b29-a46a-07f46e14385e.nrrd,...,86.417091,ZAM-AnchorInTrim1,IG_CRL,1.989520e-13,1,NaN,NaN,FAM-025-1347,0,1.0
51348,97481,TCD,Breech,FAM-025-1348-1,Dataset_C_masked_resampled_256_spc075/2020-11/...,2,2,12.0,Butterfly Network Inc,e7ad56a9-351d-4d9d-a6c0-585505314b3f.nrrd,...,103.961612,ZAM-AnchorInTrim2,IG_HCFL,4.263256e-14,1,NaN,NaN,FAM-025-1348,0,1.0

In [4]:
fig = px.histogram(df, x="n_frames")

In [5]:
fig

In [12]:
df.query('n_frames > 1000')['file_path'].sample(n=1).values[0]

'Dataset_C_masked_resampled_256_spc075/2019-03/FAM-202-0128-1_20190307_055710/4fae309e-63c9-4577-8798-73f25de250da.nrrd'